def build(context):
    context.install_files(
        "${PREFIX}/lib/borg/visual/templates/views",
        [
            "cluster.js",
            "table.js",
            "vector.js"
            ]
        )

    context.recurse("cluster");

