def build(context):
    context(
        source = [
            "__init__.py",
            "accounting.py",
            "proc.py",
            "sessions.py",
            ],
        install_path = "${PYTHONDIR}/borg/unix",
        )

