def build(context):
    install_path = "${PYTHONDIR}/borg/domains/asp"

    def cython_build(base):
        context(
            features = "c cshlib pyext",
            source = "{0}.pyx".format(base),
            target = base,
            install_path = install_path,
            )

    #cython_build("features")
    #cython_build("instance")

    context(
        source = [
            "__init__.py",
            "solvers.py",
            "features.py",
            ],
        install_path = install_path,
        )

