import os.path

def configure(context):
    # check for various required modules
    context.check_python_module("plac")
    context.check_python_module("numpy")
    context.check_python_module("scipy")
    context.check_python_module("sklearn")

    # extract numpy's installation path
    context.start_msg("Locating the NumPy module")

    try:
        import numpy

        path = os.path.dirname(numpy.__file__)
    except ImportError:
        context.end_msg(False)
        context.fatal("Unable to import NumPy")

    context.end_msg(path)

    # bring in its headers
    context.env.append_value("INCLUDES", os.path.join(path, "core/include"))

def build(context):
    install_path = "${PYTHONDIR}/borg"

    def cython_build(base):
        context(
            features = "c cshlib pyext",
            source = "{0}.pyx".format(base),
            target = base,
            install_path = install_path,
            )

    cython_build("models")
    cython_build("planners")
    cython_build("statistics")

    context(
        source = [
            "__init__.py",
            "defaults.py",
            "expenses.py",
            "portfolios.py",
            "solver_io.py",
            "storage.py",
            "regression.py",
            "fake.py",
            "util.py",
            ],
        install_path = install_path,
        )

    context.install_files(
        install_path,
        [
            "models.pxd",
            "statistics.pxd",
            ],
        )

    context.recurse("unix")
    context.recurse("domains")
    context.recurse("tools")
    context.recurse("experiments")
    context.recurse("test")

