def build(context):
    context(
        source = [
            "__init__.py",
            "test_instance.py",
            "s2v120c1200-2.cnf",
            ],
        install_path = "${PREFIX}/lib/borg/domains/max_sat/test",
        )

