def build(context):
    context(
        source = [
            "__init__.py",
            "test_opb.py",
            "test_solvers.py",
            ],
        install_path = "${PREFIX}/lib/borg/domains/pb/test",
        )

