def build(context):
    context(
        source = [
            "__init__.py",
            ],
        install_path = "${PYTHONDIR}/borg/domains",
        )

    context.recurse("max_sat")
    context.recurse("pb")
    context.recurse("sat")
    context.recurse("asp")

