def build(context):
    context.install_files(
        "${PYTHONDIR}/borg/visual/templates/core",
        [
            "bar_chart.js",
            "list.js",
            "state.js",
            "loading.js",
            "ui.js",
            ]
        )

