def build(context):
    context.install_files(
        "${PREFIX}/lib/borg/visual/templates",
        [
            "index.html",
            "borgview.css",
            "borgview.js",
            "analytics.js",
            ]
        )

    context.recurse("core")
    context.recurse("views")

