def build(context):
    context.install_files(
        "${PYTHONDIR}/borg/visual/templates/views/cluster",
        [
            "selection.js",
            "cost_plot.js",
            "success_plot.js",
            ]
        )

