def options(context):
    context.load("compiler_c")
    context.load("python")
    context.load("cython")

def configure(context):
    context.load("compiler_c")

    context.load("python")
    context.check_python_headers()
    context.check_python_version((2, 6))

    context.load("cython")

    context.env.append_unique("CFLAGS", ["-O3", "-msse2", "-mtune=generic"])

    context.recurse("borg")

def build(context):
    context.recurse("borg")

