def build(context):
    install_path = "${PYTHONDIR}/borg/domains/sat/test"

    context.install_files(
        install_path,
        [
            "example.simple.cnf",
            ],
        )

    context(
        source = [
            "__init__.py",
            "test_instance.py",
            ],
        install_path = install_path,
        )

