def build(context):
    install_path = "${PREFIX}/lib/borg/domains/sat"

    def cython_build(base):
        context(
            features = "c cshlib pyext",
            source = "{0}.pyx".format(base),
            target = base,
            install_path = install_path,
            )

    cython_build("dimacs")

    context(
        source = [
            "__init__.py",
            "features.py",
            "solvers.py",
            ],
        install_path = install_path,
        )

