def options(context):
    context.recurse("cpp")
    context.recurse("python")

def configure(context):
    context.recurse("cpp")
    context.recurse("python")

def build(context):
    context.recurse("cpp")
    context.recurse("python")

