def build(context):
    context(
        source = [
            "__init__.py",
            "get_calibration.py",
            "get_features.py",
            "run_solvers.py",
            "solve.py",
            "train.py",
            "cactus.py",
            "simulate.py",
            "evaluate_model.py",
            "evaluate_regression.py",
            "bundle_run_data.py",
            "ground.py",
            ],
        install_path = "${PYTHONDIR}/borg/tools",
        )

