def build(context):
    context(
        source = [
            "__init__.py",
            "get_calibration.py",
            "get_features.py",
            "run_solvers.py",
            "run_validation.py",
            "solve.py",
            "train.py",
            ],
        install_path = "${PYTHONDIR}/borg/tools",
        )

